#--------------------------------------#
# PROJ: Analyzing video captions on YT #
#--------------------------------------#

### init environment
rm(list = ls())

library(dplyr)
library(data.table)
library(tidyr)
library(ggplot2)
library(scales)

print(getwd())

if (!grepl("yt-captions(/)?$", getwd())) setwd("~/Desktop/Projects/yt-captions/")

path <- getwd()

### import data (raw data files + crosswalk for languages)
setwd(paste0(path, "/data/caption_tracks"))
files <- lapply(list.files(pattern = ".csv"), read.csv)

# languages encoded by BCP-47 code, see below links for info:
# https://www.mesalliance.org/wp-content/uploads/2019/07/Language-Metadata-Table-LMT-V2.0.pdf
# http://linkedvocabs.org/lingvoj/languages/all.html
# https://www.localeplanet.com/icu/fr-BE/index.html
lang_cw <- read.csv(paste0(path, "/setup/language-crosswalk.csv"))

### stack video track data + merge on language
vidtracks <- lapply(files, function(dt) {
    dt %>%
        select(channelTitle, channelId, videoTitle, videoId, 
               captionLang, captionType, videoCategory) %>%
        return()
}) %>% rbindlist() %>% 
    unique() %>% 
    left_join(lang_cw, by = c("captionLang" = "code"))

### crate a new crosswalk using any new languages
lang_cw.new <- vidtracks %>% 
    filter(!is.na(captionLang) & captionLang != "") %>%
    group_by(code = captionLang) %>%
    summarise(n_vid = n_distinct(videoId),
              .groups = "drop") %>%
    mutate(from_data = 1, .before = n_vid) %>%
    full_join(lang_cw %>% 
                  select(code, language), 
              by = "code") %>%
    relocate(language, .after = code) %>%
    arrange(code)

write.csv(lang_cw.new, paste0(path, "/setup/language-crosswalk.csv"), row.names = F)

### group by video to see which videos have caption tracks
vids <- vidtracks %>%
    group_by(videoId, videoCategory) %>%
    summarise(nonasr = sum(ifelse(!is.na(captionType) & captionType != "" & captionType != "asr", 1, 0)),
              asr = sum(ifelse(captionType == "asr", 1, 0)),
              nonen = sum(ifelse(captionLang != "" & captionLang != "en", 1, 0)),
              .groups = "drop") %>%
    mutate(captionType = case_when(asr > 0 & nonasr > 0 ~ "both",
                                   asr == 0 & nonasr > 0 ~ "only_usergen",
                                   asr > 0 & nonasr == 0 ~ "only_autogen",
                                   asr == 0 & nonasr == 0 ~ "neither"))

### summarise types of captions (only autogenerated = asr, only usergenerated, only english)
(by_type <- vids %>%
    count(captionType, has_noneng = nonen > 0) %>%
    mutate(pct = n / sum(n)))

### summarise by video category
(by_category <- vids %>%
    count(videoCategory, captionType) %>%
    pivot_wider(id_cols = "videoCategory", names_from = "captionType", values_from = "n") %>%
    mutate(across(where(is.numeric), ~ replace_na(.x, 0))) %>%
    mutate(total = neither + only_usergen + only_autogen + both,
           pct_usergen = (only_usergen + both) / total) %>%
    arrange(pct_usergen))

### plot % by category
(by_category_w_overall <- by_category %>%
    select(videoCategory, pct_usergen) %>%
    bind_rows(by_category %>%
              summarise(both = sum(both, na.rm = T), 
                        only_usergen = sum(only_usergen, na.rm = T),
                        total = sum(total)) %>%
              mutate(videoCategory = "Overall",
                     pct_usergen = sum(both, only_usergen) / total) %>%
              select(videoCategory, pct_usergen)))

data.dates <- as.Date(list.files(pattern = ".csv"), "%Y-%m-%d_%H-%M-%S_trending-vid-captions.csv")

ggplot(by_category_w_overall) +
    geom_col(aes(x = reorder(videoCategory, pct_usergen), y = pct_usergen, fill = videoCategory == "Overall")) +
    geom_text(aes(x = reorder(videoCategory, pct_usergen), y = pct_usergen, 
                  label = percent(pct_usergen, accuracy = 0.1)), hjust = 1.1, size = 3) +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = NULL, labels = percent, 
                       expand = c(0, 0), limits = c(0, .6)) +
    scale_fill_manual(values = c("#cae8fc", "#77bdee")) +
    coord_flip() +
    labs(title = "Percent of videos with user-generated captions for top trending videos",
         subtitle = paste0("Based on ", format(nrow(vids), big.mark = ","), " videos from ",
                           length(data.dates), " days (", paste0(format(c(min(data.dates), max(data.dates)), 
                                                                       "%b %d, %Y"), collapse = " - "), ")")) +
    theme_classic() +
    theme(legend.position = "none", 
          plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          plot.margin = margin(0.1, 0.25, 0.1, 0.1, "in"))

ggsave(paste0(path, "/img/pct_captions_by_category.png"), device = "png", 
       width = 8, height = 5, unit = "in")
