#--------------------------------------#
# PROJ: Analyzing video captions on YT #
#--------------------------------------#

### init environment
rm(list = ls())

library(tidyverse)
library(data.table)
library(readxl)

setwd("~/Desktop/Projects/yt-captions/data/")

### import data (raw data files + crosswalk for languages)
files <- lapply(list.files(pattern = ".csv"), read.csv)

# languages encoded by BCP-47 code, see below links for info:
# https://www.mesalliance.org/wp-content/uploads/2019/07/Language-Metadata-Table-LMT-V2.0.pdf
# http://linkedvocabs.org/lingvoj/languages/all.html
lang_cw <- read_excel("language-crosswalk.xlsx")

### stack video track data + merge on language
vidtracks <- lapply(files, function(dt) {
    dt %>%
        select(channelTitle, channelId, videoTitle, videoId, captionLang, captionType, videoCategory) %>%
        return()
}) %>% rbindlist() %>% unique() %>% left_join(lang_cw, by = c("captionLang" = "code"))

### group by video to see which videos have caption tracks
vids <- vidtracks %>%
    group_by(videoId, videoCategory) %>%
    summarise(nonasr = sum(ifelse(!is.na(captionType) & captionType != "" & captionType != "asr", 1, 0)),
              asr = sum(ifelse(captionType == "asr", 1, 0)),
              nonen = sum(ifelse(captionLang != "" & captionLang != "en", 1, 0))) %>%
    mutate(captionType = case_when(asr > 0 & nonasr > 0 ~ "both",
                                   asr == 0 & nonasr > 0 ~ "only_usergen",
                                   asr > 0 & nonasr == 0 ~ "only_autogen",
                                   asr == 0 & nonasr == 0 ~ "neither"))

### summarise types of captions (only autogenerated = asr, only usergenerated, only english)
vids %>%
    group_by(captionType, "has_noneng" = nonen > 0) %>%
    summarise(n = n()) %>%
    ungroup() %>%
    mutate(pct = n / sum(n))

### summarise by video category
vids %>%
    group_by(videoCategory, captionType) %>%
    summarise(n = n()) %>%
    pivot_wider(id_cols = "videoCategory", names_from = "captionType", values_from = "n") %>%
    mutate(total = sum(neither, only_usergen, only_autogen, both, na.rm = T),
           pct_usergen = sum(only_usergen, both, na.rm = T) / total) %>%
    arrange(pct_usergen)