#--------------------------------------#
# PROJ: Analyzing video captions on YT #
#--------------------------------------#

### init environment
rm(list = ls())

library(tidyverse)
library(data.table)
library(readxl)
library(scales)

setwd("~/Desktop/Projects/yt-captions/data/")

### import data (raw data files + crosswalk for languages)
files <- lapply(list.files(pattern = ".csv"), read.csv)

# languages encoded by BCP-47 code, see below links for info:
# https://www.mesalliance.org/wp-content/uploads/2019/07/Language-Metadata-Table-LMT-V2.0.pdf
# http://linkedvocabs.org/lingvoj/languages/all.html
lang_cw <- read_excel("setup/language-crosswalk.xlsx")

### stack video track data + merge on language
vidtracks <- lapply(files, function(dt) {
    dt %>%
        select(channelTitle, channelId, videoTitle, videoId, captionLang, captionType, videoCategory) %>%
        return()
}) %>% rbindlist() %>% unique() %>% left_join(lang_cw, by = c("captionLang" = "code"))

### identify any instances without capptionLang
vidtracks %>%
    filter(captionLang != "" & (language == "" | is.na(language))) %>%
    arrange(captionLang) %>%
    View()

### group by video to see which videos have caption tracks
vids <- vidtracks %>%
    group_by(videoId, videoCategory) %>%
    summarise(nonasr = sum(ifelse(!is.na(captionType) & captionType != "" & captionType != "asr", 1, 0)),
              asr = sum(ifelse(captionType == "asr", 1, 0)),
              nonen = sum(ifelse(captionLang != "" & captionLang != "en", 1, 0))) %>%
    mutate(captionType = case_when(asr > 0 & nonasr > 0 ~ "both",
                                   asr == 0 & nonasr > 0 ~ "only_usergen",
                                   asr > 0 & nonasr == 0 ~ "only_autogen",
                                   asr == 0 & nonasr == 0 ~ "neither"))

### summarise types of captions (only autogenerated = asr, only usergenerated, only english)
(by_type <- vids %>%
    group_by(captionType, "has_noneng" = nonen > 0) %>%
    summarise(n = n()) %>%
    ungroup() %>%
    mutate(pct = n / sum(n)))

### summarise by video category
(by_category <- vids %>%
    group_by(videoCategory, captionType) %>%
    summarise(n = n()) %>%
    pivot_wider(id_cols = "videoCategory", names_from = "captionType", values_from = "n") %>%
    mutate(total = sum(neither, only_usergen, only_autogen, both, na.rm = T),
           pct_usergen = sum(only_usergen, both, na.rm = T) / total) %>%
    arrange(pct_usergen))

### plot % by category
(by_category_w_overall <- by_category %>%
    select(videoCategory, pct_usergen) %>%
    bind_rows(by_category %>%
              group_by() %>%
              summarise(both = sum(both, na.rm = T), 
                        only_usergen = sum(only_usergen, na.rm = T),
                        total = sum(total)) %>%
              mutate(videoCategory = "Overall",
                     pct_usergen = sum(both, only_usergen) / total) %>%
              select(videoCategory, pct_usergen)))

ggplot(by_category_w_overall) +
    geom_col(aes(x = reorder(videoCategory, pct_usergen), y = pct_usergen, fill = videoCategory == "Overall")) +
    geom_text(aes(x = reorder(videoCategory, pct_usergen), y = pct_usergen, 
                  label = percent(pct_usergen)), hjust = 1.1, size = 3) +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = NULL, labels = percent, 
                       expand = c(0, 0), limits = c(0, .5)) +
    scale_fill_manual(values = c("#cae8fc", "#77bdee")) +
    coord_flip() +
    labs(title = "Percent of videos with user-generated captions for top trending videos") +
    theme_classic() +
    theme(legend.position = "none", 
          plot.title = element_text(hjust = 0.5),
          plot.margin = margin(0.1, 0.25, 0.1, 0.1, "in"))

ggsave("../pct_captions_by_category.png", device = "png", width = 8, height = 5, unit = "in")
