name: Scrape Caption Text from Videos
on:
  schedule:
      - cron: '24 16 * * *'
  push:

jobs:
  scrape-caption-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build Env
        uses: ./.github/actions/build_py_env
        with:
          requirements: data/setup/caption-scraper-reqs.txt
      - name: Run Caption Text Scraper Script
        run: pipenv run python code/scrape-captions-selenium.py --file=data/caption_text/videos_to_pull_caption_text.txt
      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 3.6.1
      - name: Install Packages
        run: |
          install.packages(c("dplyr", "data.table", "fuzzyjoin"))
        shell: Rscript {0}
      - name: Run Caption Text Cleaner Script
        run: Rscript code/clean-captions-text.R
      - name: Commit
        uses: ./.github/actions/commit
        with:
          message: new yt caption text file(s)
          what: data/caption_text